apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - networkattachdefinition.yaml
  - node.yaml
  - recurringjob.yaml
  - storageclass.yaml
secretGenerator:
  - envs:
      - longhorn-hetzner-backups/.env
    name: longhorn-hetzner-backups
    namespace: longhorn-system
    options:
      annotations:
        longhorn.io/backup-target: s3://shikanime-studio-nishir-longhorn-backups-e9750005@fsn1/
      disableNameSuffixHash: true
