apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - name: alloy-metrics-remote-cfg-k8s-monitoring
    namespace: grafana-system
    envs:
      - alloy-metrics-remote-cfg-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
  - name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
    namespace: grafana-system
    envs:
      - alloy-singleton-remote-cfg-grafana-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
  - name: alloy-logs-remote-cfg-k8s-monitoring
    namespace: grafana-system
    envs:
      - alloy-logs-remote-cfg-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
  - name: alloy-receiver-remote-cfg-k8s-monitoring
    namespace: grafana-system
    envs:
      - alloy-receiver-remote-cfg-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
  - name: alloy-profiles-remote-cfg-k8s-monitoring
    namespace: grafana-system
    envs:
      - alloy-profiles-remote-cfg-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
  - name: grafana-cloud-logs-k8s-monitoring
    namespace: grafana-system
    envs:
      - grafana-cloud-logs-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
  - name: grafana-cloud-metrics-k8s-monitoring
    namespace: grafana-system
    envs:
      - grafana-cloud-metrics-k8s-monitoring/.env
    options:
      disableNameSuffixHash: true
