apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - envs:
      - alloy-logs-remote-cfg-k8s-monitoring/.env
    name: alloy-logs-remote-cfg-k8s-monitoring
    namespace: grafana-system
    options:
      disableNameSuffixHash: true
  - envs:
      - alloy-metrics-remote-cfg-k8s-monitoring/.env
    name: alloy-metrics-remote-cfg-k8s-monitoring
    namespace: grafana-system
    options:
      disableNameSuffixHash: true
  - envs:
      - alloy-receiver-remote-cfg-k8s-monitoring/.env
    name: alloy-receiver-remote-cfg-k8s-monitoring
    namespace: grafana-system
    options:
      disableNameSuffixHash: true
  - envs:
      - alloy-singleton-remote-cfg-k8s-monitoring/.env
    name: alloy-singleton-remote-cfg-k8s-monitoring
    namespace: grafana-system
    options:
      disableNameSuffixHash: true
  - envs:
      - gc-otlp-endpoint-k8s-monitoring/.env
    name: gc-otlp-endpoint-k8s-monitoring
    namespace: grafana-system
    options:
      disableNameSuffixHash: true
  - envs:
      - grafana-cloud-metrics-k8s-monitoring/.env
    name: grafana-cloud-metrics-k8s-monitoring
    namespace: grafana-system
    options:
      disableNameSuffixHash: true
