apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - namereference.yaml
resources:
  - ../default
  - cert.yaml
configMapGenerator:
  - files:
      - whisparr/config.enc.xml
    name: whisparr-startup
secretGenerator:
  - envs:
      - whisparr/.env
    name: whisparr-pkcs12-password
