apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/tls
configurations:
  - namereference.yaml
namespace: shikanime
patches:
  - path: patch-netpol.yaml
  - path: patch-ingress.yaml
  - path: patch-sts.yaml
resources:
  - ../../base
  - cert.yaml
secretGenerator:
  - files:
      - whisparr/config.xml
    name: whisparr
  - envs:
      - whisparr/.env
    name: whisparr-pkcs12-password
