apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounts
  annotations:
    tailscale.com/proxy-class: accounts
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: accounts
      port:
        name: https
  rules:
    - http:
        paths:
          - path: /.ory/kratos/public
            pathType: Prefix
            backend:
              service:
                name: accounts-ory
                port:
                  name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos
  annotations:
    tailscale.com/proxy-class: kratos
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kratos
      port:
        name: https
