apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/longhorn
  - ../../components/node-feature
  - ../../components/shikanime
  - ../../components/tls
  - ../../components/networkpolicies
resources:
  - ../../base
