apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - svc.yaml
secretGenerator:
  - envs:
      - operator-oauth/.enc.env
    name: operator-oauth
    namespace: tailscale-system
    options:
      disableNameSuffixHash: true
