apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - svc.yaml
secretGenerator:
  - envs:
      - oauth-client/.env
    name: oauth-client
    namespace: tailscale-system
    options:
      disableNameSuffixHash: true
