apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
patches:
  - path: patch-deploy.yaml
resources:
  - ../../base
secretGenerator:
  - envs:
      - ./ftp-basic-auth/.env
    name: ftp-basic-auth
