apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - namereference.yaml
configMapGenerator:
  - files:
      - lidarr/config.enc.xml
    name: lidarr-startup
resources:
  - ../default
  - cert.yaml
secretGenerator:
  - envs:
      - lidarr/.env
    name: lidarr-pkcs12-password
