apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/tls
configurations:
  - namereference.yaml
namespace: shikanime
patches:
  - path: patch-netpol.yaml
  - path: patch-ingress.yaml
  - path: patch-sts.yaml
resources:
  - ../../base
  - cert.yaml
secretGenerator:
  - files:
      - lidarr/config.xml
    name: lidarr
  - envs:
      - lidarr/.env
    name: lidarr-pkcs12-password
