apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configurations:
  - namereference.yaml
resources:
  - cluster.yaml
  - hcloud-machine-template.yaml
  - hetzner-cluster.yaml
  - k0s-control-plane.yaml
  - k0s-worker-config-template.yaml
  - machine-deployment.yaml
secretGenerator:
  - envs:
      - hetzner/.enc.env
    name: hetzner
    namespace: nishir
