apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./copyparty/config.conf
    name: copyparty
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-svc.yaml
resources:
  - ../nishir
  - proxyclass.yaml
