apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
components:
  - ../../components/tailscale
resources:
  - ../nishir
configMapGenerator:
  - files:
      - ./copyparty/config.conf
    name: copyparty
