apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: rclone
    newName: docker.io/rclone/rclone
    newTag: 1.72.0
patches:
  - path: patch-sts.yaml
  - path: patch-ingress.yaml
  - path: patch-svc.yaml
