apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
components:
  - ../../components/tls
patches:
  - path: patch-deploy.yaml
resources:
  - ../../base
  - cert.yaml
secretGenerator:
  - envs:
      - rclone-ftp/.env
    name: rclone-ftp
  - envs:
      - rclone-htpasswd/.env
    name: rclone-htpasswd
