apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounts
spec:
  defaultBackend:
    service:
      name: accounts
      port:
        name: http
  rules:
    - http:
        paths:
          - path: /.ory/kratos/public
            pathType: Prefix
            backend:
              service:
                name: accounts-ory
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos
spec:
  defaultBackend:
    service:
      name: kratos
      port:
        name: http
