apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounts
spec:
  defaultBackend:
    service:
      name: accounts
      port:
        name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos
spec:
  defaultBackend:
    service:
      name: kratos
      port:
        name: https
