apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime/studio
components:
  - ../../components/tailscale
resources:
  - ../../base
  - ../../../../apps/catbox/overlays/telsha-tailnet
