apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - namereference.yaml
resources:
  - ../default
  - cert.yaml
configMapGenerator:
  - files:
      - radarr/config.enc.xml
    name: radarr-startup
secretGenerator:
  - envs:
      - radarr/.env
    name: radarr-pkcs12-password
