apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime/studio
configurations:
  - namereference.yaml
components:
  - ../../components/tls
resources:
  - ../../base
  - cert.yaml
patches:
  - path: patch-sts.yaml
secretGenerator:
  - envs:
      - radarr/.env
    name: radarr-pkcs12-password
  - files:
      - radarr/config.xml
    name: radarr
