apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
components:
  - ../../components/ftp
  - ../../components/ftps
  - ../../components/tls
  - ../../components/zeroconf
patches:
  - path: patch-sts.yaml
resources:
  - ../../base
  - cert.yaml
  - pvc.yaml
