apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "rclone", "tag-regex": "^(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)$" }, { "name": "bazarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: rclone
    newName: docker.io/rclone/rclone
    newTag: 1.71.2
  - name: bazarr
    newName: lscr.io/linuxserver/bazarr
    newTag: 1.5.3
labels:
  - pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: v1.5.3
resources:
  - ingress.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
