apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - envs:
      - operator-oauth/.env
    name: operator-oauth
    namespace: tailscale-system
    options:
      disableNameSuffixHash: true
