apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - namereference.yaml
components:
  - ../../components/tls
resources:
  - ../../base
  - cert.yaml
patches:
  - path: patch-sts.yaml
secretGenerator:
  - envs:
      - sonarr/.env
    name: sonarr-pkcs12-password
  - files:
      - sonarr/config.xml
    name: sonarr
