apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - namereference.yaml
resources:
  - ../default
  - cert.yaml
configMapGenerator:
  - files:
      - sonarr/config.enc.xml
    name: sonarr-startup
secretGenerator:
  - envs:
      - sonarr/.env
    name: sonarr-pkcs12-password
