apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - cert.yaml
components:
  - ../../components/tls
secretGenerator:
  - envs:
      - rclone-htpasswd/.env
    name: rclone-htpasswd
