apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - cert.yaml
secretGenerator:
  - name: qbittorrent-scripts
    files:
      - qbittorrent-scripts/qbittorrent-torrent-finished-handler.sh
