apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: rclone
    newName: docker.io/rclone/rclone
    newTag: 1.71.2
resources:
  - deploy.yaml
  - svc.yaml
labels:
  - pairs:
      app.kubernetes.io/component: file-manager
      app.kubernetes.io/name: ftp
      app.kubernetes.io/part-of: nishir-operation
      app.kubernetes.io/version: v1.71.2
