apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" }, { "name": "lidarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$", "exclude-tags": ["8.1.2135"] } ]'
images:
  - name: lidarr
    newName: lscr.io/linuxserver/lidarr
    newTag: 3.1.0
  - name: rclone
    newName: docker.io/rclone/rclone
    newTag: 1.72.0
labels:
  - pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/name: lidarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: v3.1.0
resources:
  - ingress.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
