apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix
spec:
  defaultBackend:
    service:
      name: matrix
      port:
        name: https
  rules:
    - host: matrix
      http:
        paths:
          - backend:
              service:
                name: matrix-manager
                port:
                  name: https
            path: /.well-known/matrix/mautrix
            pathType: Prefix
