apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
patches:
  - path: patch-ingress.yaml
  - path: patch-svc.yaml
resources:
  - ../nishir
  - netpol.yaml
  - proxyclass.yaml
secretGenerator:
  - name: gitea-config
    files:
      - gitea/app.ini
