apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - shikanime-default-deny.yaml
  - shikanime-allow-tailscale.yaml
  - qbittorrent-allow-media.yaml
  - prowlarr-allow-media.yaml