apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - mautrix-manager/Caddyfile
    name: mautrix-manager
namespace: shikanime
patches:
  - path: patch-ingress.yaml
resources:
  - ../nishir
  - netpol.yaml
  - proxyclass.yaml
secretGenerator:
  - files:
      - mautrix-discord/config.enc.yaml
      - mautrix-discord/registration.enc.yaml
    name: mautrix-discord
  - files:
      - mautrix-googlechat/config.enc.yaml
      - mautrix-googlechat/registration.enc.yaml
    name: mautrix-googlechat
  - files:
      - mautrix-meta/config.enc.yaml
      - mautrix-meta/registration.enc.yaml
    name: mautrix-meta
  - files:
      - mautrix-signal/config.enc.yaml
      - mautrix-signal/registration.enc.yaml
    name: mautrix-signal
  - files:
      - mautrix-slack/config.enc.yaml
      - mautrix-slack/registration.enc.yaml
    name: mautrix-slack
  - files:
      - mautrix-whatsapp/config.enc.yaml
      - mautrix-whatsapp/registration.enc.yaml
    name: mautrix-whatsapp
  - files:
      - synapse/homeserver.enc.yaml
      - synapse/matrix.taila659a.ts.net.log.config
    name: synapse
