apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
secretGenerator:
  - name: github-nishir
    namespace: arc-runners
    envs:
      - github-nishir/.env
    options:
      disableNameSuffixHash: true
