apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "copyparty", "tag-regex": "^(?P<version>.+)$" }, { "name": "rclone", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
images:
  - name: copyparty
    newName: docker.io/copyparty/dj
    newTag: 1.19.21
  - name: rclone
    newName: docker.io/rclone/rclone
    newTag: 1.72.0
labels:
  - pairs:
      app.kubernetes.io/component: file-server
      app.kubernetes.io/name: copyparty
      app.kubernetes.io/part-of: nishir-operation
      app.kubernetes.io/version: v1.19.21
resources:
  - ingress.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
  - netpol.yaml
