jobs:
  cleanup:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - env:
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.head_ref }}
        REPO: ${{ github.repository }}
      if: '!(startsWith(github.head_ref, ''gh/'') && endsWith(github.head_ref, ''/head''))'
      run: git push origin --delete "$HEAD_REF" || true
    - env:
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.head_ref }}
        REPO: ${{ github.repository }}
      if: startsWith(github.head_ref, 'gh/') && endsWith(github.head_ref, '/head')
      run: "for role in base head orig; do\n  git push origin --delete \"${HEAD_REF%/head}/$role\"\
        \ || true\ndone\n"
name: Cleanup
'on':
  pull_request:
    types:
    - closed
