jobs:
  land:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v31
    - uses: shikanime-studio/sapling-action@v6
      with:
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        sign-commits: true
        username: Operator 6O <operator6o@shikanime.studio>
name: Land
'on':
  issue_comment:
    types:
    - created
