jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.OPERATOR_APP_ID }}
        private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ steps.createGithubAppToken.outputs.token }}
    - run: nix flake check --accept-flake-config --no-pure-eval
    - run: nix develop --no-pure-eval --command devenv test
  release-tag:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - check
    runs-on: ubuntu-slim
    steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.OPERATOR_APP_ID }}
        private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - env:
        GITHUB_TOKEN: ${{ steps.createGithubAppToken.outputs.token }}
        REF_NAME: ${{ github.ref_name }}
        REPO: ${{ github.repository }}
      run: gh release create "$REF_NAME" --repo "$REPO" --generate-notes
  release-unstable:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
    - check
    runs-on: ubuntu-slim
    steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.OPERATOR_APP_ID }}
        private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - run: git push origin HEAD:refs/heads/release-unstable --force
  sync:
    needs:
    - release-unstable
    runs-on: nishir
    steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.OPERATOR_APP_ID }}
        private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ steps.createGithubAppToken.outputs.token }}
    - run: nix run nixpkgs#direnv -- direnv allow .
    - run: nix run nixpkgs#direnv -- export gha >> "$GITHUB_ENV"
    - run: nix run nixpkgs#skaffold -- run
name: Release
'on':
  push:
    branches:
    - main
    - release-[0-9]+-[0-9]+
    tags:
    - v?[0-9]+.[0-9]+.[0-9]+*
